
packages:
  - codemod
  - localization
  - localization-react
  - documentation

catalogs:
  a12ranges:
    "@com.mgmtp.a12.devtools/codemod": 2.2.2
    "@com.mgmtp.a12.devtools/eslint-config": 3.1.2
    "@com.mgmtp.a12.devtools/prettier-config": 1.1.1
    "@com.mgmtp.a12.devtools/tsconfig": 2.0.1
  fix:
    react: 19.2.4
  ranges:
    "@microsoft/api-extractor": ^7.57.7
    "@types/big.js": ^6.2.2
    "@types/luxon": ^3.6.2
    "@types/node": ^24.12.0
    "@types/react": ^19.2.14
    asciidoctor: ^3.0.4
    asciidoctor-highlight.js: ^0.4.0
    big.js: ^7.0.1
    cspell: ^9.7.0
    eslint: ^9.39.4
    eslint-plugin-import: ^2.32.0
    eslint-plugin-jsdoc: ^62.8.0
    eslint-plugin-notice: 1.1.0-rc1
    eslint-plugin-workspaces: ^0.12.1
    highlight.js: ^11.11.1
    luxon: ^3.6.1
    prettier: ^3.8.1
    react: ^19.0.0
    ts-morph: ^27.0.2
    typedoc: ^0.28.18
    typescript: ^6.0.3

# cleanup unused catalog entries during install
cleanupUnusedCatalogs: true

# no cycles between workspace dependencies
disallowWorkspaceCycles: true
# enforce version constraints from package.json
engineStrict: true

# when using "--filter", check that the filter applies to some package
failIfNoMatch: true

# do not check git status when publishing
gitChecks: false

ignoredBuiltDependencies:
  - esbuild

ignoredOptionalDependencies:
  - libxmljs2

# CI sets this to warn by default
loglevel: info

# prevent pnpm >10 from self-upgrading,
# since it doesn't use the global node_modules as target
managePackageManagerVersions: false

# enforce new packages to be at least 1 week old, except our own
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@com.mgmtp.a12.*/*'

overrides:
  lodash: ">=4.17.24"

packageManagerStrict: true

peerDependencyRules:
  allowedVersions:
    "asciidoctor-highlight.js@0.4>@asciidoctor/core": "3"

# ensure latest deps are installed when updating for audit
resolutionMode: highest

# ensure dependency build scripts (e.g. postinstall) are either ignored or approved
strictDepBuilds: true

# do not install packages where trust level decreased
trustPolicy: no-downgrade

# before "pnpm run" calls, checks if node_modules are up-to-date
# (e.g. after rebasing / checking out a branch and forgetting "pnpm install")
verifyDepsBeforeRun: warn
